name: quick test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: ./
        with:
          pip-conf: |
            Hello, world!

      - name: check it up
        run: |
          cat ~/.config/pip/pip.conf

